"""add auto start streams to opening

Revision ID: fcd69a1713c5
Revises: 9783e35f3a94
Create Date: 2026-07-11 14:15:58.697474

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fcd69a1713c5"
down_revision: Union[str, None] = "9783e35f3a94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("openings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "auto_start_streams",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.add_column(
            sa.Column("streams_started_at", sa.DateTime(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("openings", schema=None) as batch_op:
        batch_op.drop_column("streams_started_at")
        batch_op.drop_column("auto_start_streams")

    # ### end Alembic commands ###
